spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/yuge?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      connect-properties:
        config:
          decrypt: false
  jpa:
    properties:
      hibernate:
        session_factory:
#          statement_inspector: com.yuge.jpa.jpainterceptor.datarule.OwnInspector
#          session_scoped_interceptor: com.yuge.jpa.jpainterceptor.datarule.DataRuleInterceptor
          interceptor: com.yuge.jpa.jpainterceptor.datarule.DataRuleInterceptor

